#!/bin/sh
# /etc/init.d/syslog - Start and stop syslogd and klogd

case "$1" in
  start)
    echo "Starting syslogd and klogd..."
    /sbin/syslogd
    /sbin/klogd
    ;;
  stop)
    echo "Stopping syslogd and klogd..."
    killall syslogd
    killall klogd
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
